#pragma once

#define IDC_STATIC                  -1
#define IDD_CONFIG_DIALOG           101
#define IDC_RADIO_TELEX             1001
#define IDC_RADIO_SIMPLE_TELEX      1002
#define IDC_RADIO_VNI                1003
#define IDC_CHECK_AUTO_CORRECT      1004
#define IDC_GROUP_METHOD            1005
#define IDC_GROUP_OPTIONS           1006
#define IDC_STATIC_VERSION          1007
#define IDC_CHECK_ENABLE_LOG        1008
#define IDC_CHECK_ENABLE_SHORTHAND  1009
#define IDC_BUTTON_SHORTHAND_TABLE  1010
#define IDD_SHORTHAND_DIALOG        102
#define IDC_EDIT_SHORTHAND_RULES    1011
#define IDC_BUTTON_IMPORT           1012
#define IDC_BUTTON_EXPORT           1013
#define IDC_CHECK_AUTO_CAPITALIZE   1014
#define IDC_CHECK_ENABLE_APP_BLOCKLIST 1015
#define IDC_BUTTON_APP_BLOCKLIST    1016
#define IDD_APP_BLOCKLIST_DIALOG    103
#define IDC_EDIT_APP_BLOCKLIST      1017
#define IDC_CHECK_AUTO_EXCLUDE      1018
#define IDC_COMBO_CORRECTION_LEVEL  1019
#define IDC_GROUP_HOTKEY            1020
#define IDC_RADIO_HOTKEY_CTRL_SHIFT 1021
#define IDC_RADIO_HOTKEY_ALT_Z      1022
#define IDI_TRAY_ICON               1023

#define ID_TRAY_EXIT                2001
#define ID_TRAY_SETTINGS            2002
#define ID_TRAY_SHORTHAND           2003
#define ID_TRAY_METHOD_TELEX        2004
#define ID_TRAY_METHOD_STELEX       2005
#define ID_TRAY_METHOD_VNI          2006
#define ID_TRAY_TOGGLE_SHORTHAND    2007
#define ID_TRAY_TOGGLE_AUTOCORRECT  2008

#ifndef IDAPPLY
#define IDAPPLY                     3
#endif
