#pragma once

#define IDC_STATIC                  -1
#define IDD_CONFIG_DIALOG           101
#define IDC_RADIO_TELEX             1001
#define IDC_RADIO_SIMPLE_TELEX      1002
#define IDC_RADIO_VNI                1003
#define IDC_CHECK_AUTO_CORRECT      1004
#define IDC_GROUP_METHOD            1005
#define IDC_GROUP_OPTIONS           1006
#define IDC_STATIC_VERSION          1007
#define IDC_CHECK_ENABLE_LOG        1008
#define IDC_CHECK_ENABLE_SHORTHAND  1009
#define IDC_BUTTON_SHORTHAND_TABLE  1010
#define IDD_SHORTHAND_DIALOG        102
#define IDC_EDIT_SHORTHAND_RULES    1011
#define IDC_BUTTON_IMPORT           1012
#define IDC_BUTTON_EXPORT           1013
#define IDC_CHECK_AUTO_CAPITALIZE   1014
#define IDC_CHECK_ENABLE_APP_PROFILES 1015
#define IDC_BUTTON_APP_PROFILES     1016
#define IDD_APP_PROFILES_DIALOG     103
#define IDC_LIST_APP_PROFILES       1017
#define IDC_CHECK_AUTO_APP_PROFILES 1018
#define IDC_COMBO_CORRECTION_LEVEL  1019
#define IDC_GROUP_HOTKEY            1020
#define IDC_RADIO_HOTKEY_CTRL_SHIFT 1021
#define IDC_RADIO_HOTKEY_ALT_Z      1022
#define IDI_TRAY_ICON               1023
#define IDC_BUTTON_DIRECT_APPS      1024
#define IDD_DIRECT_APPS_DIALOG      104
#define IDC_EDIT_DIRECT_APPS        1025
#define IDI_APP_ICON                105
#define IDI_TRAY_V_ICON             107
#define IDI_TRAY_E_ICON             108
#define IDC_CHECK_AUTO_START        1026
#define IDC_GROUP_LANGUAGE          1027
#define IDC_RADIO_LANG_VIE          1028
#define IDC_RADIO_LANG_ENG          1029
#define IDC_STATIC_CORRECTION_LEVEL 1030
#define IDC_STATIC_DIRECT_APPS      1031
#define IDC_STATIC_SHORTHAND_DESC   1032
#define IDC_STATIC_APP_PROFILES_DESC 1033
#define IDC_STATIC_DIRECT_DESC      1034
#define IDC_BUTTON_CORRECTION_HELP  1035
#define IDC_STATIC_ENGLISH_PROTECTION 1036
#define IDC_COMBO_ENGLISH_PROTECTION  1037
#define IDC_COMBO_APP_PROFILE_MODE  1038
#define IDC_STATIC_APP_PROFILE_MODE 1039
#define IDC_BUTTON_ADD_CURRENT_APP  1040
#define IDC_BUTTON_BROWSE_APP       1041
#define IDC_BUTTON_REMOVE_APP_PROFILE 1042
#define IDC_STATIC_STARTUP_DESC     1043
#define IDC_GROUP_APP_PROFILES      1044
#define IDC_CHECK_SMART_UNDO        1045
#define IDC_GROUP_UTILITIES         1046
#define IDC_CHECK_SMART_CONTEXT_PROTECTION 1047
#define IDC_STATIC_HOTKEY_MODE      1048
#define IDC_STATIC_STARTUP_SECTION  1049
#define IDC_STATIC_FOOTER_SEPARATOR 1050


#define ID_TRAY_EXIT                2001
#define ID_TRAY_SETTINGS            2002
#define ID_TRAY_SHORTHAND           2003
#define ID_TRAY_METHOD_TELEX        2004
#define ID_TRAY_METHOD_STELEX       2005
#define ID_TRAY_METHOD_VNI          2006
#define ID_TRAY_TOGGLE_SHORTHAND    2007
#define ID_TRAY_TOGGLE_AUTOCORRECT  2008
#define ID_TRAY_METHOD_OFF          2009

#ifndef IDAPPLY
#define IDAPPLY                     3
#endif
