#pragma once

#include <cstddef>
#include <string_view>

namespace vn_ime::core::speller::data {

// Curated Vietnamese two-word phrases used only by Experimental segmentation.
inline constexpr std::wstring_view COMMON_BIGRAMS[] = {
    L"an ninh", L"an toàn", L"an tâm", L"anh chàng", L"anh em", L"anh hùng", L"anh trai", L"áo khoác",
    L"ba mẹ", L"bài báo", L"bài hát", L"bài học", L"bài tập", L"bạn bè", L"bạn gái", L"bạn thân", L"bạn trai",
    L"bản chất", L"bản thân", L"bảo vệ", L"bao gồm", L"bao lâu", L"bao nhiêu", L"bắt đầu", L"băn khoăn", L"bận rộn",
    L"bất ngờ", L"bây giờ", L"bến xe", L"bệnh nhân", L"bệnh viện", L"bị thương", L"bình an", L"bình thường",
    L"bình tĩnh", L"bí mật", L"bỗng nhiên", L"bóng đá", L"bóng tối", L"bối rối", L"bộ đội", L"bộ phim", L"bởi vì",
    L"cá nhân", L"cái gì", L"cam kết", L"can đảm", L"cảnh báo", L"cảnh sát", L"cạnh tranh", L"cao cấp", L"cám ơn",
    L"cảm ơn", L"cảm thấy", L"cảm xúc", L"cẩn thận", L"câu chuyện", L"câu hỏi", L"cây cối", L"cần thiết", L"cấp cứu",
    L"cầu nguyện", L"cầu thủ", L"chắc chắn", L"chắc là", L"chăm chỉ", L"chăm sóc", L"chân thành", L"chấp nhận",
    L"chất lượng", L"chậm chạp", L"chạy trốn", L"chỉ đạo", L"chia sẻ", L"chiến dịch", L"chiến thắng", L"chiến tranh",
    L"chiều nay", L"chính phủ", L"chính quyền", L"chính xác", L"chịu đựng", L"chó mèo", L"chống lại", L"chỗ ngồi",
    L"chủ nghĩa", L"chủ nhật", L"chủ tịch", L"chủ yếu", L"chuẩn bị", L"chúc mừng", L"chúng ta", L"chúng tôi",
    L"chuyên gia", L"chuyển động", L"chuyến đi", L"chuyện gì", L"chưa từng", L"chương trình",
    L"danh dự", L"danh sách", L"danh tiếng", L"dành cho", L"dân số", L"dân tộc", L"dấu hiệu", L"dây chuyền",
    L"dẻo dai", L"dễ dàng", L"dễ thương", L"dịch vụ", L"diễn biến", L"diễn đàn", L"diễn ra", L"diễn viên",
    L"diện tích", L"dũng cảm", L"dọn dẹp", L"dòng sông", L"dư luận", L"dự án", L"dự báo", L"dự định", L"dữ dội",
    L"đại diện", L"đại học", L"đảm bảo", L"đàn bà", L"đàn ông", L"đáng kể", L"đáng sợ", L"đánh giá", L"đạo diễn",
    L"đạo đức", L"đặc biệt", L"đặc điểm", L"đắt đỏ", L"đầu tư", L"đấu tranh", L"đất nước", L"đầu tiên", L"đầy đủ",
    L"đề nghị", L"đề tài", L"để lại", L"đến nỗi", L"đều đặn", L"điều kiện", L"điều tra", L"điện ảnh", L"điện thoại",
    L"đỉnh cao", L"định hướng", L"đọc sách", L"đóng cửa", L"đóng góp", L"đồng bào", L"đồng chí", L"đồng hồ",
    L"đồng nghiệp", L"đồng thời", L"đồng tiền", L"đồng ý", L"đột nhiên", L"đội bóng", L"đổi mới", L"đối diện",
    L"đối mặt", L"đối phó", L"đối phương", L"đối thủ", L"đối tượng", L"đường phố",
    L"gai góc", L"gan dạ", L"gắn bó", L"gắt gao", L"gặp gỡ", L"gặp mặt", L"gần đây", L"gần gũi", L"gật đầu", L"gây ra",
    L"ghi chép", L"ghi nhận", L"ghét bỏ", L"ghê gớm", L"gia đình", L"gia tăng", L"giá cả", L"giá trị", L"giám đốc",
    L"gian khổ", L"giao dịch", L"giao tiếp", L"giáo dục", L"giáo sư", L"giáo viên", L"giàu có", L"giấc mơ", L"giận dữ",
    L"giờ đây", L"giới thiệu", L"giữ gìn",
    L"hà nội", L"hành động", L"hành khách", L"hành lý", L"hành vi", L"hạnh phúc", L"hát hò", L"hay là", L"hằng ngày",
    L"hấp dẫn", L"hậu quả", L"hệ thống", L"hi vọng", L"hiện đại", L"hiện nay", L"hiện ra", L"hiện tại", L"hiện tượng",
    L"hiểu biết", L"hình ảnh", L"hình như", L"hình thức", L"hòa bình", L"hoàn cảnh", L"hoàn thành", L"hoàn toàn",
    L"hoàng hôn", L"hoảng hốt", L"hoạt động", L"học sinh", L"học tập", L"hôm nay", L"hôm qua", L"hôn nhân",
    L"hỗn loạn", L"hội đồng", L"hội nghị", L"hợp lý", L"hợp tác", L"hứa hẹn", L"hư hỏng", L"hy vọng",
    L"kết luận", L"kết quả", L"kết thúc", L"kêu gọi", L"kế hoạch", L"kể từ", L"kể cả", L"khách hàng", L"khách sạn",
    L"khai thác", L"khám phá", L"kháng chiến", L"khẳng định", L"khắp nơi", L"khắc nghiệt", L"khẩn cấp", L"khẩu trang",
    L"khen ngợi", L"khéo léo", L"khiếp sợ", L"khó khăn", L"khóa học", L"khoa học", L"khoản tiền", L"khoảng cách",
    L"khóc lóc", L"khỏe mạnh", L"khổng lồ", L"không chỉ", L"không có", L"không gian", L"không khí", L"không sao",
    L"không thể", L"khuyên bảo", L"khuyến khích",
    L"la hét", L"lạ lùng", L"lạc quan", L"làm việc", L"lãng mạn", L"lãnh đạo", L"lão hóa", L"lấp lánh", L"lấp lửng",
    L"lập tức", L"lâu dài", L"lâu nay", L"lấy lại", L"lễ hội", L"lên tiếng", L"liên lạc", L"liên quan", L"liên tục",
    L"linh hoạt", L"lịch sự", L"lịch sử", L"lo lắng", L"lo sợ", L"loài người", L"loại bỏ", L"loay hoay", L"long trọng",
    L"lỡ làng", L"lớn lên", L"lợi ích", L"lợi nhuận", L"lộn xộn", L"lố bịch", L"lừa đảo", L"lựa chọn", L"lực lượng",
    L"lưu ý",
    L"ma quỷ", L"mặc dù", L"mặc kệ", L"máy bay", L"máy móc", L"máy tính", L"mạnh mẽ", L"mảnh mai", L"mạo hiểm",
    L"may mắn", L"mỉm cười", L"miễn phí", L"miêu tả", L"minh bạch", L"mù mịt", L"mục đích", L"mục tiêu", L"muốn nói",
    L"mùa hè", L"mùa đông", L"mùa thu", L"mùa xuân", L"mưa bão", L"mượt mà", L"mỹ phẩm", L"mỹ thuật",
    L"nam giới", L"nạn nhân", L"năng lượng", L"năng lực", L"nắng nóng", L"nắm bắt", L"nỗ lực", L"năm nay", L"nằm ngủ",
    L"nâng cao", L"nấu ăn", L"nước mắt", L"nước ngoài", L"nụ cười", L"nữ giới", L"ngạc nhiên", L"ngày mai", L"ngày nay",
    L"ngon lành", L"ngọt ngào", L"ngồi xuống", L"ngôn ngữ", L"nghệ thuật", L"nghĩ lại", L"nghĩ ngợi", L"nghĩa là",
    L"nghĩa vụ", L"nghiêm trọng", L"nghiên cứu", L"nghiệp vụ", L"nghỉ ngơi",
    L"phá hoại", L"phá sản", L"phát biểu", L"phát hiện", L"phát sóng", L"phát thanh", L"phát triển", L"pháp luật",
    L"pháp lý", L"phân biệt", L"phân tích", L"phản ánh", L"phản đối", L"phản ứng", L"phạm vi", L"phạm tội", L"phẫn nộ",
    L"phòng ngự", L"phỏng vấn", L"phụ nữ", L"phục hồi", L"phục vụ", L"phụ thuộc", L"phức tạp", L"phương pháp",
    L"phương tiện",
    L"quan hệ", L"quan sát", L"quan tâm", L"quan trọng", L"quản lý", L"quản trị", L"quảng cáo", L"quang cảnh",
    L"quyết định", L"quy định", L"quy mô", L"quyển sách", L"quyền lợi", L"quốc gia", L"quốc tế",
    L"rải rác", L"rảnh rỗi", L"rắc rối", L"rạng rỡ", L"rất nhiều", L"rầm rộ", L"rực rỡ", L"rủi ro", L"rút lui", L"rừng núi",
    L"sai lầm", L"sản phẩm", L"sản xuất", L"sang trọng", L"sáng kiến", L"sáng sủa", L"sáng tạo", L"sắp xếp", L"sắm sửa",
    L"sắt thép", L"sâu sắc", L"sẽ có", L"sinh hoạt", L"sinh viên", L"suy nghĩ", L"sự cố", L"sự kiện", L"sự thật", L"sự việc",
    L"sức khỏe", L"sấm sét", L"sực nhớ",
    L"tai nạn", L"tài chính", L"tài khoản", L"tài liệu", L"tài năng", L"tài sản", L"tác dụng", L"tác giả", L"tác phẩm",
    L"tái tạo", L"tạm thời", L"tàn bạo", L"tán thành", L"tăng cường", L"tập trung", L"tất cả", L"tất nhiên", L"tâm lý",
    L"tâm sự", L"tấn công", L"tận tình", L"tập thể", L"tên tuổi", L"tha thứ", L"thắc mắc", L"tham gia", L"tham khảo",
    L"tham quan", L"thảm họa", L"thanh niên", L"thành công", L"thành lập", L"thành phần", L"thành phố", L"thành thật",
    L"thành tựu", L"thay đổi", L"thay vì", L"thái độ", L"thao tác", L"thảo luận", L"thân thiện", L"thần kinh", L"thần tượng",
    L"thật ra", L"thật sự", L"thầy giáo", L"thế giới", L"thế kỷ", L"thế nào", L"thể dục", L"thể hiện", L"thể thao",
    L"thiết bị", L"thiết kế", L"thiết lập", L"thiên nhiên", L"thiên tài", L"thiếu niên", L"thỉnh thoảng", L"thị trường",
    L"thỏa thuận", L"thoải mái", L"thói quen", L"thông báo", L"thông minh", L"thông qua", L"thông tin", L"thời gian",
    L"thời kỳ", L"thời tiết", L"thời trang", L"thu nhập", L"thu hút", L"thụ động", L"thủ đô", L"thủ tục", L"thú vị",
    L"thử thách", L"thực hiện", L"thực ra", L"thực sự", L"thực tế", L"thương mại", L"thường xuyên", L"thưởng thức",
    L"trân trọng", L"tranh luận", L"trao đổi", L"trách nhiệm", L"tránh xa", L"trái đất", L"trang bị", L"trang trí",
    L"trang web", L"trả lời", L"tràn ngập", L"trạng thái", L"trầm trọng", L"trận đấu", L"trẻ em", L"trên đời",
    L"trên mạng", L"triết lý", L"triển khai", L"triệu chứng", L"trình độ", L"trí tuệ", L"trong sáng", L"trong suốt",
    L"trọng tâm", L"trở lại", L"trở nên", L"trở thành", L"trung bình", L"trung tâm", L"trung thực", L"trưởng thành",
    L"trừ khi", L"trực tiếp", L"tút tát",
    L"u buồn", L"u ám", L"u sầu", L"ung thư", L"ủng hộ", L"ưu đãi", L"ưu điểm", L"ưu tiên", L"ủy ban",
    L"va chạm", L"vai trò", L"văn bản", L"văn hóa", L"văn minh", L"văn phòng", L"vận chuyển", L"vận động", L"vấn đề",
    L"vất vả", L"vấp ngã", L"vật chất", L"vật lý", L"vẻ đẹp", L"vô cùng", L"vô lý", L"vô tình", L"vui vẻ", L"vũ khí",
    L"vũ trụ", L"vương quốc", L"vượt qua", L"vững chắc", L"Việt Nam",
    L"xa lạ", L"xã hội", L"xác nhận", L"xác định", L"xao xuyến", L"xây dựng", L"xảy ra", L"xâm phạm", L"xấu xí",
    L"xem xét", L"xin chào", L"xin lỗi", L"xóa bỏ", L"xót xa", L"xuất bản", L"xuất hiện", L"xuất sắc", L"xung quanh",
    L"xuống dốc", L"xử lý",
    L"y học", L"y tế", L"yếu kém", L"yêu cầu", L"yêu thương", L"yếu tố", L"ý kiến", L"ý nghĩa", L"ý thức", L"ý tưởng",
    L"bán hàng", L"bạn hàng", L"công nghệ", L"kiểm tra", L"kinh nghiệm", L"phần mềm", L"phong phú", L"xúc tác"
};

inline constexpr size_t COMMON_BIGRAMS_SIZE = sizeof(COMMON_BIGRAMS) / sizeof(COMMON_BIGRAMS[0]);

} // namespace vn_ime::core::speller::data
