#!/usr/bin/env python3
"""Generate Neokey's Vietnamese syllable frequency header.

The syllable list itself is not touched: this reads DICTIONARY out of
speller_data.hpp and emits one tier per entry, in the same order, so a lookup is
the index the existing binary search already finds. The two arrays must stay in
lockstep, which is why the count is asserted at compile time and the source
files are hashed here.

A tier is floor(log2(occurrences + 1)) - one tier is one doubling. Counts are
not shipped: the corrector only ever asks whether one syllable is
overwhelmingly commoner than another, and a tier gap answers exactly that while
staying stable if the corpus is recounted at a different size.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import unicodedata
from pathlib import Path

ENTRY = re.compile(r'L"([^"\\]*)"')
MAX_TIER = 255


def read_dictionary_order(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    words = [
        unicodedata.normalize("NFC", match.group(1))
        for match in ENTRY.finditer(text)
        if match.group(1)
    ]
    if not words:
        raise ValueError(f"{path}: no dictionary entries parsed")
    if len(words) != len(set(words)):
        raise ValueError(f"{path}: dictionary has duplicate entries")
    if words != sorted(words):
        # The lookup is a binary search, so an unsorted dictionary would break
        # far more than this table.
        raise ValueError(f"{path}: dictionary is not sorted")
    return words


def read_tiers(path: Path) -> dict[str, int]:
    tiers: dict[str, int] = {}
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(None, 1)
        if len(parts) != 2:
            raise ValueError(f"{path}:{line_number}: expected '<tier> <syllable>'")
        tier_text, word = parts
        if not tier_text.isdigit():
            raise ValueError(f"{path}:{line_number}: tier must be a number")
        tier = int(tier_text)
        if tier > MAX_TIER:
            raise ValueError(f"{path}:{line_number}: tier above {MAX_TIER}")
        word = unicodedata.normalize("NFC", word)
        if word in tiers:
            raise ValueError(f"{path}:{line_number}: duplicate syllable: {word}")
        tiers[word] = tier
    if not tiers:
        raise ValueError(f"{path}: no tiers parsed")
    return tiers


def format_array(values: list[int], width: int = 24) -> str:
    lines: list[str] = []
    for start in range(0, len(values), width):
        chunk = ", ".join(str(value) for value in values[start : start + width])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


def generate_header(order: list[str], tiers: dict[str, int],
                    dictionary: Path, source: Path) -> str:
    missing = [word for word in order if word not in tiers]
    if missing:
        raise ValueError(
            f"{source}: {len(missing)} dictionary syllables have no tier, "
            f"first is {missing[0]!r}. Every entry needs a line so the arrays "
            f"stay aligned."
        )
    extra = [word for word in tiers if word not in set(order)]
    if extra:
        raise ValueError(
            f"{source}: {len(extra)} tiers name syllables the dictionary does "
            f"not have, first is {extra[0]!r}"
        )

    values = [tiers[word] for word in order]
    unseen = sum(1 for value in values if value == 0)
    return f"""// Generated by tools/generate_vietnamese_frequency.py
// from {source.as_posix()}
// against {dictionary.as_posix()}
// Source SHA-256: {hashlib.sha256(source.read_bytes()).hexdigest()}
// Dictionary SHA-256: {hashlib.sha256(dictionary.read_bytes()).hexdigest()}
// Do not edit this file manually.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace vn_ime::core::speller::data {{

// One entry per DICTIONARY entry, in the same order, so the index the binary
// search finds is the index of the tier. A tier is floor(log2(occurrences+1)):
// one tier is one doubling, and 0 means the corpus never showed that syllable.
inline constexpr size_t kSyllableFrequencyCount = {len(values)};
inline constexpr uint8_t kSyllableFrequencyMaxTier = {max(values)};
inline constexpr size_t kSyllableFrequencyUnseen = {unseen};

inline constexpr std::array<uint8_t, kSyllableFrequencyCount>
    kSyllableFrequencyTiers{{
{format_array(values)}
}};

}} // namespace vn_ime::core::speller::data
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dictionary", type=Path,
                        default=Path("src/core/speller_data.hpp"))
    parser.add_argument("--source", type=Path,
                        default=Path("data/vietnamese_syllable_frequency.txt"))
    parser.add_argument("--output", type=Path,
                        default=Path("src/core/vietnamese_frequency_generated.hpp"))
    args = parser.parse_args()

    order = read_dictionary_order(args.dictionary)
    tiers = read_tiers(args.source)
    header = generate_header(order, tiers, args.dictionary, args.source)
    args.output.write_text(header, encoding="utf-8", newline="\n")
    print(f"wrote {args.output} for {len(order)} syllables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
