#!/usr/bin/env python3
"""Generate Neokey's allocation-free English lexicon header."""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path


MIN_WORD_LENGTH = 2
MAX_WORD_LENGTH = 20
LETTERS = "abcdefghijklmnopqrstuvwxyz"
WORD_PATTERN = re.compile(r"[a-z]{2,20}")
TIER_VALUE = {"C": 1, "E": 2}


def read_words(path: Path) -> dict[str, int]:
    words: dict[str, int] = {}
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) != 2 or parts[0] not in TIER_VALUE:
            raise ValueError(f"{path}:{line_number}: expected '<C|E> <word>'")
        tier, word = parts
        if not WORD_PATTERN.fullmatch(word):
            raise ValueError(
                f"{path}:{line_number}: word must be lowercase ASCII and "
                f"{MIN_WORD_LENGTH}-{MAX_WORD_LENGTH} letters: {word!r}"
            )
        if word in words:
            raise ValueError(f"{path}:{line_number}: duplicate word: {word}")
        words[word] = TIER_VALUE[tier]
    if not words:
        raise ValueError(f"{path}: lexicon is empty")
    return words


def format_array(values: list[int], width: int = 12) -> str:
    lines: list[str] = []
    for start in range(0, len(values), width):
        chunk = ", ".join(str(value) for value in values[start : start + width])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


def generate_header(words: dict[str, int], source: Path) -> str:
    source_sha256 = hashlib.sha256(source.read_bytes()).hexdigest()
    ordered: list[tuple[str, int]] = []
    bucket_starts: list[int] = []
    for length in range(MIN_WORD_LENGTH, MAX_WORD_LENGTH + 1):
        for first in LETTERS:
            bucket_starts.append(len(ordered))
            ordered.extend(
                sorted(
                    (word, tier)
                    for word, tier in words.items()
                    if len(word) == length and word[0] == first
                )
            )
    bucket_starts.append(len(ordered))

    blob_parts: list[str] = []
    offsets: list[int] = []
    tiers: list[int] = []
    offset = 0
    for word, tier in ordered:
        offsets.append(offset)
        tiers.append(tier)
        blob_parts.append(f'    "{word}\\0"')
        offset += len(word) + 1

    common_count = sum(tier == 1 for tier in tiers)
    extended_count = sum(tier == 2 for tier in tiers)
    bucket_count = (MAX_WORD_LENGTH - MIN_WORD_LENGTH + 1) * len(LETTERS)

    return f"""// Generated by tools/generate_english_lexicon.py from {source.as_posix()}.
// Source SHA-256: {source_sha256}
// Do not edit this file manually.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace vn_ime::core::speller::data {{

inline constexpr size_t kEnglishLexiconMinWordLength = {MIN_WORD_LENGTH};
inline constexpr size_t kEnglishLexiconMaxWordLength = {MAX_WORD_LENGTH};
inline constexpr size_t kEnglishLexiconBucketCount = {bucket_count};
inline constexpr size_t kEnglishLexiconWordCount = {len(ordered)};
inline constexpr size_t kEnglishLexiconCommonCount = {common_count};
inline constexpr size_t kEnglishLexiconExtendedCount = {extended_count};

inline constexpr char kEnglishLexiconBlob[] =
{chr(10).join(blob_parts)}
    ;

inline constexpr std::array<uint32_t, kEnglishLexiconWordCount>
    kEnglishLexiconOffsets{{
{format_array(offsets)}
}};

// 1 = Common/Balanced, 2 = Extended/English First.
inline constexpr std::array<uint8_t, kEnglishLexiconWordCount>
    kEnglishLexiconTiers{{
{format_array(tiers, width=24)}
}};

inline constexpr std::array<uint16_t, kEnglishLexiconBucketCount + 1>
    kEnglishLexiconBucketStarts{{
{format_array(bucket_starts)}
}};

consteval bool ValidateEnglishLexiconData() noexcept {{
    if (kEnglishLexiconBucketStarts.back() != kEnglishLexiconWordCount ||
        kEnglishLexiconCommonCount + kEnglishLexiconExtendedCount !=
            kEnglishLexiconWordCount) {{
        return false;
    }}
    size_t common_count = 0;
    size_t extended_count = 0;
    for (size_t i = 0; i < kEnglishLexiconWordCount; ++i) {{
        if (kEnglishLexiconOffsets[i] >= sizeof(kEnglishLexiconBlob) ||
            kEnglishLexiconTiers[i] < 1 || kEnglishLexiconTiers[i] > 2) {{
            return false;
        }}
        common_count += kEnglishLexiconTiers[i] == 1;
        extended_count += kEnglishLexiconTiers[i] == 2;
        if (i > 0 && kEnglishLexiconOffsets[i] <= kEnglishLexiconOffsets[i - 1]) {{
            return false;
        }}
    }}
    if (common_count != kEnglishLexiconCommonCount ||
        extended_count != kEnglishLexiconExtendedCount) {{
        return false;
    }}
    for (size_t i = 1; i < kEnglishLexiconBucketStarts.size(); ++i) {{
        if (kEnglishLexiconBucketStarts[i] <
                kEnglishLexiconBucketStarts[i - 1] ||
            kEnglishLexiconBucketStarts[i] > kEnglishLexiconWordCount) {{
            return false;
        }}
    }}
    return true;
}}

static_assert(kEnglishLexiconWordCount < UINT16_MAX);
static_assert(ValidateEnglishLexiconData());

}} // namespace vn_ime::core::speller::data
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--data", type=Path, default=Path("data/english_bilingual_lexicon.txt")
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/core/english_lexicon_generated.hpp"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    try:
        content = generate_header(read_words(args.data), args.data)
    except (OSError, ValueError) as error:
        print(error, file=sys.stderr)
        return 2

    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except OSError:
            current = ""
        if current != content:
            print(f"Generated lexicon is stale: {args.output}", file=sys.stderr)
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
